### ISSUE TITLE
Portfolio v2.0.0 (Revamp)

### ISSUE THREAD

**Issue by akashbagchi** [akashbagchi/akashbagchi.github.io#2]
### Summary

Revamp the portfolio to bring content up-to-date, add new pages and reimagine visually.

### TODO

- [x] New pages
   - [x] About
   - [x] #10
- [x] Update color theme
   - [x] (TENTATIVE) Dark Mode
- [x] Update links
   - [x]  Digital Garden
   - [x] Resume
   - [x] LinkedIn
- [x] Text Content
- [x] Refactor file structure
